version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - vkamiansky
  assignees:
  - vkamiansky
  labels:
  - dependencies
  ignore:
  - dependency-name: Nuke.Common
    versions:
    - 5.0.2
    - 5.1.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: Moq
    versions:
    - 4.16.0
